apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotten
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rotten
  template:
    metadata:
      labels:
        app: rotten
    spec:    
      containers:
        - name: rotten
          image: stuardbr/rotten-potatoes:latest
          ports:
            - containerPort: 80
            
---
apiVersion: v1
kind: Service
metadata:
  name: rotten
spec:
  selector:
    app: rotten
  ports:
      - protocol: TCP
        port: 80
        nodePort: 30000
  type: NodePort
