apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:    
      containers:
        - name: mongodb
          image: mongo:5.0.5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd
---
# Servicec do MnogoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
  type: ClusterIP
---
# Deployment da pagina
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotten
spec:
  selector:
    matchLabels:
      app: rotten
  template:
    metadata:
      labels:
        app: rotten
    spec:    
      containers:
        - name: rotten
          image: stuardbr/rotten-potatoes:latest
          ports:
            - containerPort: 5000
          env: 
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: mongouser
            - name: MONGODB_PASSORD
              value: mongopwd
            
---

apiVersion: v1
kind: Service
metadata:
  name: rotten
spec:
  selector:
    app: rotten
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort
